name: flutter_appauth
description: This plugin provides an abstraction around the Android and iOS AppAuth SDKs so it can be used to communicate with OAuth 2.0 and OpenID Connect providers
version: 4.0.1
homepage: https://github.com/MaikuB/flutter_appauth/tree/master/flutter_appauth

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth_platform_interface:
    git:
      url: https://github.com/Xfers/flutter_appauth
      path: flutter_appauth_platform_interface
      ref: 387e4085f545fd593612a81fea35847ab60c7e0f

flutter:
  plugin:
    platforms:
      android:
        package: io.crossingthestreams.flutterappauth
        pluginClass: FlutterAppauthPlugin
      ios:
        pluginClass: FlutterAppauthPlugin
      macos:
        pluginClass: FlutterAppauthPlugin
